### Site Settings ###
title               : MistikEdu
description         : >-
                      Hola! Soy Luis, profe de FP y esta es mi caja de pandora con
                      apuntes para informática de FP, enlaces, herramientas digitales, sobre informática,
                      apuntes para oposiciones y presentaciones para módulo.
url                 : "https://luisjsolsona.github.io"
baseurl             : ""
repository          : luisjsolsona/luisjsolsona.github.io
remote_theme        : yousinix/portfolYOU
open_new_tab        : false                    # Opens external URLs in new tab (works for posts, projects and navbar only)

### Plugins ###
plugins:
  - jemoji

### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md

### Author Info ###
author:
  name              : Luis Solsona
  image             : /assets/img/Luis-Solsona.jpg
  github            : luisjsolsona
  linkedin          : luisjorgesolsonamartinez

### Posts ###
permalink: /blog/:title

### Collections ###
collections:
  apuntes_fp_informatica:
    output: true
    permalink: /apuntes-fp-informatica/:path/
  elements:
    output: true

### Disqus ###
disqus:
  shortname: ""                  # Your website Shortname on disqus

### Analytics ###
analytics:
  enabled: false
  google:
    tracking_id: your-google-tracking-id

### Buy me a coffee ###
buymeacoffee:
  enabled: false
  username: luisjsolmar
  color: "#007bff"
  message: "Invitate a un café al menos..."
  description: "Support me on Buy me a coffee!"

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "apuntes_fp_informatica"
    values:
      layout: "page"

  - scope:                      # Elements only
      path: ""
      type: "elements"
    values:
      layout: "element"

  - scope:
      path: ""
      type: "posts"
    values:
      comments: false

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
  - documentation
  - documentation/**
